/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Apresentacao;

import static java.awt.SystemColor.menu;

/**
 *
 * @author Caio
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        // Abrir automatizado
        this.setExtendedState(Menu.MAXIMIZED_BOTH);
        this.setTitle("Sistema de Reservas para Hotéis e Pousadas"); // alterando título
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JDesktopPane();
        LB_acesso = new javax.swing.JLabel();
        LB_id = new javax.swing.JLabel();
        LB_nome = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menu_sistema = new javax.swing.JMenu();
        menu_arquivo = new javax.swing.JMenu();
        sub_menu_quartos = new javax.swing.JMenuItem();
        sub_menu_produtos = new javax.swing.JMenuItem();
        menu_reservas = new javax.swing.JMenu();
        sub_menu_reservas = new javax.swing.JMenuItem();
        sub_menu_clientes = new javax.swing.JMenuItem();
        sub_menu_pagamentos = new javax.swing.JMenuItem();
        menu_consultas = new javax.swing.JMenu();
        menu_configuracoes = new javax.swing.JMenu();
        sub_menu_usuarios = new javax.swing.JMenuItem();
        menu_ferramentas = new javax.swing.JMenu();
        menu_suporte = new javax.swing.JMenu();
        menu_sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu.setBackground(new java.awt.Color(255, 255, 255));

        LB_acesso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LB_acesso.setForeground(new java.awt.Color(255, 255, 255));
        LB_acesso.setText("ID");
        menu.add(LB_acesso);
        LB_acesso.setBounds(1240, 30, 120, 20);

        LB_id.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LB_id.setForeground(new java.awt.Color(255, 255, 255));
        LB_id.setText("ID");
        menu.add(LB_id);
        LB_id.setBounds(1100, 30, 60, 20);

        LB_nome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        LB_nome.setForeground(new java.awt.Color(255, 255, 255));
        LB_nome.setText("ID");
        menu.add(LB_nome);
        LB_nome.setBounds(1170, 30, 60, 20);

        menu_sistema.setBorder(null);
        menu_sistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/Inicio.png"))); // NOI18N
        menu_sistema.setMnemonic('f');
        menu_sistema.setText("Sistema");
        menu_sistema.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBar.add(menu_sistema);

        menu_arquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/arquivo.png"))); // NOI18N
        menu_arquivo.setMnemonic('e');
        menu_arquivo.setText("Arquivo");
        menu_arquivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sub_menu_quartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/quartos.png"))); // NOI18N
        sub_menu_quartos.setMnemonic('t');
        sub_menu_quartos.setText("Quartos");
        sub_menu_quartos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sub_menu_quartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_menu_quartosActionPerformed(evt);
            }
        });
        menu_arquivo.add(sub_menu_quartos);

        sub_menu_produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/produtos.png"))); // NOI18N
        sub_menu_produtos.setMnemonic('y');
        sub_menu_produtos.setText("Produtos");
        sub_menu_produtos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sub_menu_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_menu_produtosActionPerformed(evt);
            }
        });
        menu_arquivo.add(sub_menu_produtos);

        menuBar.add(menu_arquivo);

        menu_reservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/Reservas.png"))); // NOI18N
        menu_reservas.setMnemonic('h');
        menu_reservas.setText("Reservas");
        menu_reservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sub_menu_reservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/reservas-consumos.png"))); // NOI18N
        sub_menu_reservas.setMnemonic('c');
        sub_menu_reservas.setText("Reservas e Consumos");
        sub_menu_reservas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sub_menu_reservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_menu_reservasActionPerformed(evt);
            }
        });
        menu_reservas.add(sub_menu_reservas);

        sub_menu_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/clientes.png"))); // NOI18N
        sub_menu_clientes.setMnemonic('a');
        sub_menu_clientes.setText("Clientes");
        sub_menu_clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sub_menu_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_menu_clientesActionPerformed(evt);
            }
        });
        menu_reservas.add(sub_menu_clientes);

        sub_menu_pagamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/pagamentos.png"))); // NOI18N
        sub_menu_pagamentos.setText("Pagamentos");
        sub_menu_pagamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_reservas.add(sub_menu_pagamentos);

        menuBar.add(menu_reservas);

        menu_consultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/buscar.png"))); // NOI18N
        menu_consultas.setText("Consultas");
        menu_consultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBar.add(menu_consultas);

        menu_configuracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/configurações.png"))); // NOI18N
        menu_configuracoes.setText("Configurações");
        menu_configuracoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sub_menu_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/usuario 32x32.png"))); // NOI18N
        sub_menu_usuarios.setText("Usuários e Acessos");
        sub_menu_usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sub_menu_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_menu_usuariosActionPerformed(evt);
            }
        });
        menu_configuracoes.add(sub_menu_usuarios);

        menuBar.add(menu_configuracoes);

        menu_ferramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/ferramentas.png"))); // NOI18N
        menu_ferramentas.setText("Ferramentas");
        menu_ferramentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBar.add(menu_ferramentas);

        menu_suporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/ajuda.png"))); // NOI18N
        menu_suporte.setText("Suporte");
        menu_suporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuBar.add(menu_suporte);

        menu_sair.setBackground(new java.awt.Color(255, 51, 0));
        menu_sair.setForeground(new java.awt.Color(255, 0, 0));
        menu_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/images/icones/sair.png"))); // NOI18N
        menu_sair.setText("Sair");
        menu_sair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_sairMouseClicked(evt);
            }
        });
        menuBar.add(menu_sair);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sub_menu_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_menu_produtosActionPerformed
        FormularioProdutos produtos = new FormularioProdutos(); 
        menu.add(produtos); 
        produtos.toFront(); 
        produtos.setVisible(true); 
    }//GEN-LAST:event_sub_menu_produtosActionPerformed

    private void sub_menu_reservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_menu_reservasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub_menu_reservasActionPerformed

    private void sub_menu_quartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_menu_quartosActionPerformed
        FormularioQuartos quartos = new FormularioQuartos(); 
        menu.add(quartos); // area menu recebe o formulário de quartos
        quartos.toFront(); // iniciar na frente do formulario
        quartos.setVisible(true); // tornar visível
    }//GEN-LAST:event_sub_menu_quartosActionPerformed

    private void sub_menu_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_menu_clientesActionPerformed
        FormularioClientes clientes = new FormularioClientes(); 
        menu.add(clientes); 
        clientes.toFront(); 
        clientes.setVisible(true); 
    }//GEN-LAST:event_sub_menu_clientesActionPerformed

    private void sub_menu_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_menu_usuariosActionPerformed
       FormularioFuncionarios funcionarios = new FormularioFuncionarios(); 
        menu.add(funcionarios); 
        funcionarios.toFront(); 
        funcionarios.setVisible(true);
    }//GEN-LAST:event_sub_menu_usuariosActionPerformed

    private void menu_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_sairMouseClicked
        this.dispose(); // fecha o formulário
    }//GEN-LAST:event_menu_sairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel LB_acesso;
    public static javax.swing.JLabel LB_id;
    public static javax.swing.JLabel LB_nome;
    public static javax.swing.JDesktopPane menu;
    private javax.swing.JMenuBar menuBar;
    public static javax.swing.JMenu menu_arquivo;
    public static javax.swing.JMenu menu_configuracoes;
    private javax.swing.JMenu menu_consultas;
    private javax.swing.JMenu menu_ferramentas;
    private javax.swing.JMenu menu_reservas;
    private javax.swing.JMenu menu_sair;
    private javax.swing.JMenu menu_sistema;
    private javax.swing.JMenu menu_suporte;
    private javax.swing.JMenuItem sub_menu_clientes;
    private javax.swing.JMenuItem sub_menu_pagamentos;
    private javax.swing.JMenuItem sub_menu_produtos;
    private javax.swing.JMenuItem sub_menu_quartos;
    private javax.swing.JMenuItem sub_menu_reservas;
    private javax.swing.JMenuItem sub_menu_usuarios;
    // End of variables declaration//GEN-END:variables

}
